// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqHFmxKl0KcosNZS8NCgmNVUIqT3bJsxI',
    appId: '1:1013423485138:web:29ccdbc63da967d79e7d0b',
    messagingSenderId: '1013423485138',
    projectId: 'pimpim-e4b35',
    authDomain: 'pimpim-e4b35.firebaseapp.com',
    storageBucket: 'pimpim-e4b35.firebasestorage.app',
    measurementId: 'G-8CHEE121K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNW_Pw1LspXAACjtRYt2bsEaoCzFJjYoo',
    appId: '1:1013423485138:android:b24271064023537c9e7d0b',
    messagingSenderId: '1013423485138',
    projectId: 'pimpim-e4b35',
    storageBucket: 'pimpim-e4b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPHz0U6RDWnFH-PCqniEpd-oTTpYI326k',
    appId: '1:1013423485138:ios:6878cd7e9d1ee4c29e7d0b',
    messagingSenderId: '1013423485138',
    projectId: 'pimpim-e4b35',
    storageBucket: 'pimpim-e4b35.firebasestorage.app',
    iosBundleId: 'com.example.pim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPHz0U6RDWnFH-PCqniEpd-oTTpYI326k',
    appId: '1:1013423485138:ios:6878cd7e9d1ee4c29e7d0b',
    messagingSenderId: '1013423485138',
    projectId: 'pimpim-e4b35',
    storageBucket: 'pimpim-e4b35.firebasestorage.app',
    iosBundleId: 'com.example.pim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqHFmxKl0KcosNZS8NCgmNVUIqT3bJsxI',
    appId: '1:1013423485138:web:c1e793675817b6ed9e7d0b',
    messagingSenderId: '1013423485138',
    projectId: 'pimpim-e4b35',
    authDomain: 'pimpim-e4b35.firebaseapp.com',
    storageBucket: 'pimpim-e4b35.firebasestorage.app',
    measurementId: 'G-YVQGQT7W95',
  );
}
